In [1]:
!gdown 1bwRmKkPwmLKiqOgQ_LnKH0Vsc3mJKmVR

Downloading...
From: https://drive.google.com/uc?id=1bwRmKkPwmLKiqOgQ_LnKH0Vsc3mJKmVR
To: /content/cars24-car-price-cleaned.csv
100% 1.69M/1.69M [00:00<00:00, 48.3MB/s]

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
class LinearRegression:

  def __init__(self, learning_rate = 0.1, iteration = 5):
    self.learning_rate = learning_rate
    self.iteration = iteration

  def predict(self, X):
    return np.dot(X, self.W) + self.b

  def r2_score(self, X, y):
    y_ = self.predict(X) # I have not created this yet, will come later
    ss_res = np.sum((y - y_) ** 2)
    ss_total = np.sum((y - y.mean()) ** 2)

    return 1 - (ss_res/ss_total)

  def update_weights(self):

    Y_pred = self.predict(self.X)

    dW = - ((2 * self.X.T).dot(self.Y - Y_pred))/ self.m

    db = - ( 2 * np.sum(self.Y - Y_pred)) / self.m

    self.W = self.W - (self.learning_rate  * dW)
    self.b = self.b - (self.learning_rate * db)

    return self


  def fit(self, X, Y):

    self.m, self.d = X.shape

    # weight initialization

    self.W = np.zeros(self.d)
    self.b = 0
    self.X = X
    self.Y = Y

    self.error_list = []

    for i in range(self.iteration):
      self.update_weights()
      Y_pred = X.dot(self.W) + self.b
      error = np.square(np.subtract(Y, Y_pred)).mean()
      self.error_list.append(error)
    return self

In [4]:
df = pd.read_csv('cars24-car-price-cleaned.csv')
df.head()

,selling_price,year,km_driven,mileage,engine,max_power,age,make,model,Individual,Trustmark Dealer,Diesel,Electric,LPG,Petrol,Manual,5,>5
0,1.20,2012.0,120000,19.70,796.0,46.30,11.0,MARUTI,ALTO STD,1,0,0,0,0,1,1,1,0
1,5.50,2016.0,20000,18.90,1197.0,82.00,7.0,HYUNDAI,GRAND I10 ASTA,1,0,0,0,0,1,1,1,0
2,2.15,2010.0,60000,17.00,1197.0,80.00,13.0,HYUNDAI,I20 ASTA,1,0,0,0,0,1,1,1,0
3,2.26,2012.0,37000,20.92,998.0,67.10,11.0,MARUTI,ALTO K10 2010-2014 VXI,1,0,0,0,0,1,1,1,0
4,5.70,2015.0,30000,22.77,1498.0,98.59,8.0,FORD,ECOSPORT 2015-2021 1.5 TDCI TITANIUM BSIV,0,0,1,0,0,0,1,1,0

In [5]:
df["make"]=df.groupby("make")["selling_price"].transform("mean")
df["model"]=df.groupby("model")["selling_price"].transform("mean")


from sklearn.preprocessing import MinMaxScaler
min_max_scaler = MinMaxScaler()



df1=pd.DataFrame(min_max_scaler.fit_transform(df[['year', 'km_driven', 'mileage', 'engine', 'max_power',
       'age', 'make', 'model', 'Individual', 'Trustmark Dealer', 'Diesel',
       'Electric', 'LPG', 'Petrol', 'Manual', '5', '>5']]),columns= ['year', 'km_driven', 'mileage', 'engine', 'max_power',
       'age', 'make', 'model', 'Individual', 'Trustmark Dealer', 'Diesel',
       'Electric', 'LPG', 'Petrol', 'Manual', '5', '>5'])
df1

# please don't act like shivam, split data before you apply transformation!!!!!

,year,km_driven,mileage,engine,max_power,age,make,model,Individual,Trustmark Dealer,Diesel,Electric,LPG,Petrol,Manual,5,>5
0,0.689655,0.031553,0.135345,0.117891,0.066506,0.310345,0.194048,0.041550,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0
1,0.827586,0.005237,0.128448,0.177281,0.123994,0.172414,0.232517,0.218382,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0
2,0.620690,0.015764,0.112069,0.177281,0.120773,0.379310,0.232517,0.149143,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0
3,0.689655,0.009711,0.145862,0.147808,0.100000,0.310345,0.194048,0.093193,1.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0
4,0.793103,0.007869,0.161810,0.221860,0.150709,0.206897,0.252367,0.313574,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19815,0.862069,0.018258,0.168879,0.202014,0.099919,0.137931,0.484670,0.328028,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
19816,0.931034,0.004711,0.116379,0.203347,0.138647,0.068966,0.194048,0.330632,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0
19817,0.793103,0.017606,0.147759,0.221860,0.158647,0.206897,0.318156,0.200656,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0
19818,0.827586,1.000000,0.103448,0.322719,0.217391,0.172414,0.324782,0.377671,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,1.0
19819,0.931034,0.003395,0.120690,0.221712,0.181320,0.068966,0.258412,0.519465,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [6]:
y = df["selling_price"]
y

0         1.20
1         5.50
2         2.15
3         2.26
4         5.70
         ...
19815     6.50
19816     9.25
19817     4.25
19818    12.25
19819    12.00
Name: selling_price, Length: 19820, dtype: float64

In [7]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df1,y,test_size=0.2,random_state= 10)

In [8]:
model = LinearRegression(iteration=1200)

In [9]:
model.fit(X_train,y_train)

In [10]:
model.predict(X_test)

array([ 1.80062144,  4.87259708, 20.19567196, ...,  8.81949507,
        3.49227225,  5.54356009])

In [11]:
model.W

year                 2.855929
km_driven           -0.453551
mileage             -1.117041
engine               1.908561
max_power            2.742976
age                 -3.515266
make                 2.782204
model               16.067876
Individual          -0.137464
Trustmark Dealer    -0.170975
Diesel               0.013552
Electric             0.125232
LPG                  0.184528
Petrol              -0.167846
Manual              -0.193688
5                   -0.278838
>5                  -0.269345
dtype: float64

In [12]:
model.r2_score(X_test,y_test)

0.9440105629842346

In [13]:
from sklearn.linear_model import LinearRegression

model1 = LinearRegression()

model1.fit(X_train, y_train)

LinearRegression()

In [20]:
model1.coef_

array([ 1.40953319e+13, -1.13183594e+01, -5.19306072e+00,  1.41779457e+00,
        8.46444276e-01,  1.40953319e+13,  1.36384488e+00,  1.77082960e+01,
       -1.20185997e-01, -1.47495780e-01,  1.09756740e-01,  2.60301824e+00,
        2.86238522e-01, -2.25197546e-01, -9.61050898e-02, -2.24622169e-01,
       -3.97336932e-01])

In [19]:
model1.feature_names_in_()

TypeError: 'numpy.ndarray' object is not callable

In [15]:
model1.score(X_test,y_test)

0.9436274915781044